iris_mlp:
  model : "mlp"
  parameters:
    dropout_p: 0.2
    bn: true
  train_parameters:
    batch_size: 16
    lr: 0.01
    epochs: 50

mnist_mlp:
  model : "mlp"
  parameters:
    dropout_p: 0.2
    bn: true
  train_parameters:
    batch_size: 32
    lr: 0.001
    epochs: 20

mnist_cnn:
  model : "cnn"
  parameters:
    dropout_p: 0.2
    bn: true
  train_parameters:
    batch_size: 32
    lr: 0.001
    epochs: 20