# 모델 이름 지정(default):
#   model_parameters:
#     model : "iris_MLP", "MNIST_MLP" , "CNN" 중 택1
#     dropout_p: 0.2 (0.0 지정 시 dropout 설정 x)
#     bn: true (미지정 시 batch nomalization 적용 x. false 자동 설정)
#   train_parameters:
#     lr: 0.01
#     epochs: 50
#     optim : "SGD" (optim 미지정 시 Adam자동 선택)
#     loss_type : "MSE" (loss_type 미지정 시 CE 자동 선택)
#   data_parameters:
#     dataset: "iris" , "MNIST" , "fashion-MNIST" 중 택1
#     batch_size: 16
#     augmentation: True (augmentation 미지정 시 False. augmentation 적용 안함. 반드시 mnist류 데이터 에서만 사용할것.)

iris_mlp:
  model_parameters:
    model : "iris_MLP"
    dropout_p: 0.2
    bn: true
  train_parameters:
    lr: 0.01
    epochs: 50
  data_parameters:
    dataset: "iris"
    batch_size: 16


mnist_mlp:
  model_parameters:
    model : "MNIST_MLP"
    dropout_p: 0.2
    bn: true
  train_parameters:
    lr: 0.001
    epochs: 30
  data_parameters:
    dataset: "MNIST"
    batch_size: 32
    augmentation: True

mnist_cnn:
  model_parameters:
    model : "CNN"
    dropout_p: 0.2
    bn: true
  train_parameters:
    lr: 0.001
    epochs: 30
  data_parameters:
    dataset: "fashion-MNIST"
    batch_size: 32