# iris_mlp(default):
#   model_parameters:
#     model : "iris_MLP"
#     dropout_p: 0.2
#     bn: true
#   train_parameters:
#     lr: 0.01
#     epochs: 50
#     optim : "SGD" (optim 미지정 시 Adam자동 선택)
#     loss_type : "MSE" (loss_type 미지정 시 CE 자동 선택)
#   data_parameters:
#     dataset: "iris"
#     batch_size: 16

iris_mlp:
  model_parameters:
    model : "iris_MLP"
    dropout_p: 0.2
    bn: true
  train_parameters:
    lr: 0.01
    epochs: 50
  data_parameters:
    dataset: "iris"
    batch_size: 16

mnist_mlp:
  model_parameters:
    model : "MNIST_MLP"
    dropout_p: 0.2
    bn: true
  train_parameters:
    lr: 0.001
    epochs: 20
  data_parameters:
    dataset: "MNIST"
    batch_size: 32

mnist_cnn:
  model_parameters:
    model : "CNN"
    dropout_p: 0.2
    bn: true
  train_parameters:
    lr: 0.001
    epochs: 20
  data_parameters:
    dataset: "fashion-MNIST"
    batch_size: 32